---
name: Metrics
"on":
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  discussions: read
  issues: read
  id-token: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_stargazers: yes
          plugin_notable: yes
          config_timezone: "Europe/Madrid"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
